plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/fpolania/VAS/landing/.output/public"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run generate"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]