plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/fpolania/repos/vas/landing/.output/public"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/fpolania/repos/vas/landing"
command = "npm run generate"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]