// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/23/2026, 10:10:14 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/fpolania/repos/vas/landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fpolania/repos/vas/landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fpolania/repos/vas/landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fpolania/repos/vas/landing/plugins/**/*.{js,ts,mjs}","/Users/fpolania/repos/vas/landing/composables/**/*.{js,ts,mjs}","/Users/fpolania/repos/vas/landing/utils/**/*.{js,ts,mjs}","/Users/fpolania/repos/vas/landing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fpolania/repos/vas/landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/fpolania/repos/vas/landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/fpolania/repos/vas/landing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;